public class Problem12 {

    /*
    Problem 12 - Highly divisible triangular number

    The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?
     */

    public static void main(String[] args) {
        int minDivisors = 500;
        int divisors = 0;
        int level = 0;
        int number = 0;
        int highest = 0;
        while (divisors <= minDivisors) {
            level++;
            number += level;
            divisors = divisorsCounter(number);
            System.out.println(number + " - " + divisors);
            if (divisors > highest) {
                highest = divisors;
            }
        }
        System.out.println(number);
    }

    public static int divisorsCounter(int num) {
        int counter = 1;
        for (int i = 2; i <= Math.sqrt(num); i++) {
            if (num % i == 0) {
                counter++;
            }
        }
        return counter*2;
    }
}
